const DOSIMETRY_API_PREFIX = '/dm';

export enum LoginApiConstant {
  REDIRECT_TO_LOGIN = ''
}

export const DmApiConstant = {
  GET_ALL_LOCATIONS: DOSIMETRY_API_PREFIX+'/location',
  GET_ALL_TYPEREFS: DOSIMETRY_API_PREFIX+'/typeref',
  GET_ALL_NUCLIDES: DOSIMETRY_API_PREFIX+'/nuclide',
  GET_ALL_TYPEGROUPS: DOSIMETRY_API_PREFIX+'/typegroupref',
  SAVE_TYPEGROUP_REF: DOSIMETRY_API_PREFIX+'/typegroupref',
  GET_ALL_EMPLOYEES: DOSIMETRY_API_PREFIX+'/personparticipant',
  GET_ALL_EXTERNAL_DOSIMETER: DOSIMETRY_API_PREFIX+'/edr',
  SAVE_EXTERNAL_DOSE_RESULT: DOSIMETRY_API_PREFIX+'/edr',
  GET_ALL_INTERNAL_DOSIMETER: DOSIMETRY_API_PREFIX+'/idr',
  SAVE_INTERNAL_DOSE_RESULT: DOSIMETRY_API_PREFIX+'/idr',
  GET_ALL_DOSIMETER_BY_PARTICIPANTID: DOSIMETRY_API_PREFIX+'/participant',
  GET_ALL_DASHBOARD_COUNT: DOSIMETRY_API_PREFIX+'/stg/dashboard/count',
  GET_REJECT_PARTICIPANT_RECORDLIST: DOSIMETRY_API_PREFIX+'/stg/participant/reject',
  GET_REJECT_EDR_RECORDLIST: DOSIMETRY_API_PREFIX+'/stg/edr/reject',
  GET_REJECT_PERSONNEL_RECORDLIST: DOSIMETRY_API_PREFIX+'/person/reject/flag',
  GET_LOGGED_USER_DETAILS: DOSIMETRY_API_PREFIX+'/login/details',
  GET_PARTICIPANT_REJECTION_DETAILS: DOSIMETRY_API_PREFIX+'/stg/participant',
  SAVE_PARTICIPANT_REJECTION_DETAILS: DOSIMETRY_API_PREFIX+'/stg/participant',
  GET_EDR_REJECTION_DETAILS: DOSIMETRY_API_PREFIX+'/stg/edr',
  SAVE_EDR_REJECTION_DETAILS: DOSIMETRY_API_PREFIX+'/stg/edr',
  GET_ALL_ACCOUNTS: DOSIMETRY_API_PREFIX+'/account',
  GET_ALL_INTAKE_RETENTION: DOSIMETRY_API_PREFIX+'/intakeretention',
  GET_PERSON_DETAILS: DOSIMETRY_API_PREFIX+'/person',
  GET_PERSON_DETAILS_BY_ID: DOSIMETRY_API_PREFIX+'/person/id',
  SAVE_ALL_ACCOUNTS: DOSIMETRY_API_PREFIX+'/account',
  SAVE_ALL_INTAKE_RETENTION: DOSIMETRY_API_PREFIX+'/intakeretention',
  SAVE_ALL_NUCLIDES: DOSIMETRY_API_PREFIX+'/nuclide',
  SAVE_ALL_LOCATIONS: DOSIMETRY_API_PREFIX+'/location',
  SAVE_PERSON_DETAILS: DOSIMETRY_API_PREFIX+'/person',
  GET_FLAG_PERSONNEL_DETAILS : DOSIMETRY_API_PREFIX+ '/person/id',
  SAVE_FLAG_PERSONNEL_DETAILS : DOSIMETRY_API_PREFIX+ '/person',
  GET_EDR_PROCESS : DOSIMETRY_API_PREFIX+ '/stg/edr/process',
  GET_PARTICIPANT_PROCESS : DOSIMETRY_API_PREFIX+ '/stg/participant/process',
  GET_JOB_PROCESS : DOSIMETRY_API_PREFIX+ '/stg/job/process', 
}

